name: Eduardo Grajeda Blandón
description: My personal website.

permalink: /:title/

collections:
  notes:
    output: true
    permalink: /:title/

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
    - Gemfile
    - Gemfile.lock
    - Makefile
    - LICENSE
    - README.md
    - CNAME
    - vendor
